# Generated by Django 4.1.2 on 2022-10-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_lyric_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
