# Generated by Django 4.1.2 on 2022-10-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
