# Generated by Django 4.1.2 on 2022-10-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_artiste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
